In [8]:
import numpy as np

a = np.random.rand(5)

In [9]:
print(a)

[0.86710692 0.42821804 0.71435872 0.21107505 0.038055  ]


In [10]:
print(a.shape) #not a row or col vec, it is a rank 1 array.

(5,)


Insteady can explicitly instantiate a 5,1 rank 2 array.

In [11]:
np.dot(a, a.T)

1.4915543374308398

In [12]:
a = np.random.rand(5,1)

In [13]:
print(a)

[[0.60264528]
 [0.5965206 ]
 [0.11589115]
 [0.04662223]
 [0.97587738]]


In [14]:
print(np.dot(a, a.T)) # A 5x5 matrix.

[[0.36318133 0.35949033 0.06984126 0.02809667 0.5881079 ]
 [0.35949033 0.35583683 0.06913146 0.02781112 0.58213096]
 [0.06984126 0.06913146 0.01343076 0.0054031  0.11309556]
 [0.02809667 0.02781112 0.0054031  0.00217363 0.04549758]
 [0.5881079  0.58213096 0.11309556 0.04549758 0.95233666]]


In [19]:
a = np.random.rand(5) # don't use this

a = np.random.rand(5, 1) # col vector
a = np.random.rand(1, 5) # row vec

Can use an assert statment to make sure things are working as they should.

In [31]:
assert a.shape == (1, 5), "Not right!"

In [26]:
x = 10
assert x > 0
print('x is a positive number.')

x is a positive number.


In [27]:
a.shape

(1, 5)

In [39]:
a = np.random.rand(3,4)
b = np.random.rand(4,1)
print(a)
print(b)

[[0.07534814 0.23956908 0.55462258 0.24128562]
 [0.85239973 0.64077224 0.45601724 0.67128254]
 [0.67534329 0.04389055 0.41896694 0.15665468]]
[[0.82074826]
 [0.92848592]
 [0.4003237 ]
 [0.55830117]]


In [40]:
c = a+b.T
print(c)

[[0.8960964  1.168055   0.95494629 0.79958679]
 [1.67314799 1.56925816 0.85634094 1.22958371]
 [1.49609155 0.97237648 0.81929064 0.71495585]]


In [41]:
a*b

ValueError: operands could not be broadcast together with shapes (3,4) (4,1) 

In [ ]:
a*b + a*c - b+c
a*(b+c) - b+c